config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  get 'home/about'
  get 'friends/show'
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:primeiro_nome, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
  
  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<div class ="mb-3 " >
  <%= form_with(model: friend) do |form| %>
    <div >
      <%= form.label :First_name, style: "display: block", class:"form-label" %>
      <%= form.text_field :primeiro_nome  ,class:"form-control", placeholder:"Insert your first name"%>
    </div>

    <div>
      <%= form.label :last_name, style: "display: block" %>
      <%= form.text_field :last_name, class:"form-control", placeholder:"Insert your last name"%>
    </div>

    <div>
      <%= form.label :email, style: "display: block" %>
      <%= form.text_field :email, class:"form-control", placeholder:"Insert your email" %>
    </div>

    <div>
      <%= form.label :phone, style: "display: block" %>
      <%= form.text_field :phone, class:"form-control", placeholder:"Insert your phone number" %>
    </div>

    <div>
      <%= form.label :twitter, style: "display: block" %>
      <%= form.text_field :twitter, class: "form-control", placeholder:"Insert your twitter" %>
    </div>

    <div style="padding-top: 1%">
      <%= form.submit :submit, class:"btn btn-success"%>
    </div>

  
    <% if friend.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

        <ul>
          <% friend.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <%end%>
</div>

app/views/friends/_friend.html.erb
<table id="<%= dom_id friend%>" class="table table-dark table-hover">
  <thead >
    <tr>
      <th scope="col">#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Twitter</th>
    </tr>
  </thead>
  <tbody >
    <tr>
      <th scope="row">1</th>
      <td><%= friend.primeiro_nome%></td>
      <td><%= friend.last_name%></td>
      <td><%= friend.email%></td>
      <td><%= friend.phone%></td>
      <td><%= friend.twitter%></td>
    </tr>
  </tbody>
</table>

<!-- <div id="<%= dom_id friend %>">
  <p>
    <strong>Primeiro nome:</strong>
    <%= friend.primeiro_nome %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div> -->

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friends</h1>

<div id="friends">
  <% @friends.each do |friend| %>
    <%= render friend %>
    <%= link_to "Show this friend", friend, class:"btn btn-success"%>
  <% end %>
</div>
<%= link_to "New friend", new_friend_path, class:"btn btn-success" %>

app/views/friends/new.html.erb
<h1>New friend</h1>
<%= render "form", friend: @friend %>
<br>
<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend) %> |
  <%= link_to "Back to friends", friends_path %>

  <%= button_to "Destroy this friend", @friend, method: :delete %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <%= link_to 'Site Rails', root_path, class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li>
            <%= link_to "Add friends",new_friend_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Friends list", friends_path ,class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "About Us", home_about_path ,class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", devise__path, class: "nav-link"%>
          </li>
          <li>
            <%= link_to "Sign In  ", devise__path, class: "nav-link"%>
          </li>
          <li>
            <%= link_to "Sign Out"%>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

app/views/home/about.html.erb
<h1>About page</h1>
This website was developed to manage the classmates that work with me 

app/views/home/index.html.erb
<h1>FRIEND MANAGER WEBPAGE</h1>
<p>Here you can controll all your relations </p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Site Rails</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'home/header'%>
    <div class = 'container'>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <p class = "notice"><%= notice %></p>
    <p class = "alert"><%= alert %></p>
  </body>
</html>